apiVersion: v1
entries:
  crossplane:
  - apiVersion: v1
    appVersion: 1.9.1
    created: "2023-03-08T21:42:30.896334+01:00"
    description: Crossplane is an open source Kubernetes add-on that enables platform
      teams to assemble infrastructure from multiple vendors, and expose higher level
      self-service APIs for application teams to consume.
    digest: 7decf38fb6b368b0182d8008caf6905ef7705f4709df1a9ccbe2c88b1cb7858f
    home: https://crossplane.io
    icon: https://crossplane.io/images/favicon_192x192.png
    keywords:
    - cloud
    - infrastructure
    - services
    - application
    - database
    - cache
    - bucket
    - infra
    - app
    - ops
    - gcp
    - azure
    - aws
    - alibaba
    - cloudsql
    - rds
    - s3
    - azuredatabase
    - asparadb
    - gke
    - aks
    - eks
    maintainers:
    - email: info@crossplane.io
      name: Crossplane Maintainers
    name: crossplane
    urls:
    - https://adamma-da.github.io/publish-chart-circleci/charts/crossplane-1.9.1.tgz
    version: 1.9.1
generated: "2023-03-08T21:42:30.895568+01:00"
