apiVersion: v1
entries:
  crossplane:
  - apiVersion: v1
    appVersion: 1.9.8
    created: "2023-03-09T17:01:35.47979+01:00"
    description: Crossplane is an open source Kubernetes add-on that enables platform
      teams to assemble infrastructure from multiple vendors, and expose higher level
      self-service APIs for application teams to consume.
    digest: 91a2f73562ba9c061a07f7fba9d9b63fa30e807a3e1e6fc380c4dfdada98f807
    home: https://crossplane.io
    icon: https://crossplane.io/images/favicon_192x192.png
    keywords:
    - cloud
    - infrastructure
    - services
    - application
    - database
    - cache
    - bucket
    - infra
    - app
    - ops
    - gcp
    - azure
    - aws
    - alibaba
    - cloudsql
    - rds
    - s3
    - azuredatabase
    - asparadb
    - gke
    - aks
    - eks
    maintainers:
    - email: info@crossplane.io
      name: Crossplane Maintainers
    name: crossplane
    urls:
    - https://github.com/adamma-da/publish-chart-circleci/releases/download/crossplane-2.0.0/crossplane-2.0.0.tgz
    version: 2.0.0
generated: "2023-03-09T17:01:35.479811+01:00"
