apiVersion: v1
entries:
  crossplane:
  - apiVersion: v1
    appVersion: 1.9.8
    created: "2023-03-09T16:36:58.300763+01:00"
    description: Crossplane is an open source Kubernetes add-on that enables platform
      teams to assemble infrastructure from multiple vendors, and expose higher level
      self-service APIs for application teams to consume.
    digest: c0fb03a9aa43aee933aaae20d42797d39fbf89236ecc6cc5c4eb9b7227c2fa3f
    home: https://crossplane.io
    icon: https://crossplane.io/images/favicon_192x192.png
    keywords:
    - cloud
    - infrastructure
    - services
    - application
    - database
    - cache
    - bucket
    - infra
    - app
    - ops
    - gcp
    - azure
    - aws
    - alibaba
    - cloudsql
    - rds
    - s3
    - azuredatabase
    - asparadb
    - gke
    - aks
    - eks
    maintainers:
    - email: info@crossplane.io
      name: Crossplane Maintainers
    name: crossplane
    urls:
    - https://github.com/adamma-da/publish-chart-circleci/releases/download/crossplane-1.9.8/crossplane-1.9.8.tgz
    version: 1.9.8
generated: "2023-03-09T16:36:58.300769+01:00"
