apiVersion: v1
entries:
  crossplane:
  - apiVersion: v1
    appVersion: 1.9.8
    created: "2023-03-09T17:16:06.98669+01:00"
    description: Crossplane is an open source Kubernetes add-on that enables platform
      teams to assemble infrastructure from multiple vendors, and expose higher level
      self-service APIs for application teams to consume.
    digest: de28eab9760cd041aabae8262d788005e47e76d1b22d2053df0f7ee3d9861ab5
    home: https://crossplane.io
    icon: https://crossplane.io/images/favicon_192x192.png
    keywords:
    - cloud
    - infrastructure
    - services
    - application
    - database
    - cache
    - bucket
    - infra
    - app
    - ops
    - gcp
    - azure
    - aws
    - alibaba
    - cloudsql
    - rds
    - s3
    - azuredatabase
    - asparadb
    - gke
    - aks
    - eks
    maintainers:
    - email: info@crossplane.io
      name: Crossplane Maintainers
    name: crossplane
    urls:
    - https://github.com/adamma-da/publish-chart-circleci/releases/download/crossplane-2.0.3/crossplane-2.0.3.tgz
    version: 2.0.3
generated: "2023-03-09T17:16:06.986704+01:00"
