apiVersion: v1
entries:
  crossplane:
  - apiVersion: v1
    appVersion: 1.9.1
    created: "2023-03-09T15:05:14.806742+01:00"
    description: Crossplane is an open source Kubernetes add-on that enables platform
      teams to assemble infrastructure from multiple vendors, and expose higher level
      self-service APIs for application teams to consume.
    digest: 83d6de9289219f911f33f6398a1077b2900719e111d8bc361572b6c24700a0ca
    home: https://crossplane.io
    icon: https://crossplane.io/images/favicon_192x192.png
    keywords:
    - cloud
    - infrastructure
    - services
    - application
    - database
    - cache
    - bucket
    - infra
    - app
    - ops
    - gcp
    - azure
    - aws
    - alibaba
    - cloudsql
    - rds
    - s3
    - azuredatabase
    - asparadb
    - gke
    - aks
    - eks
    maintainers:
    - email: info@crossplane.io
      name: Crossplane Maintainers
    name: crossplane
    urls:
    - https://github.com/adamma-da/publish-chart-circleci/releases/download/crossplane-1.9.3/crossplane-1.9.3.tgz
    version: 1.9.3
generated: "2023-03-09T15:05:14.806756+01:00"
